server:
  port: 8090
app:
  appSecret: 2db8f546a503d11ff59b25f2d6eb7eba
  appId: wx80b6deccdf5913cb
  token: kfjpqwoeijfals
  encodingAESKey: 1LTq4VVveuPPfeSlG05HsO7AUDy1DBPFcggJaWH2Hyy

spring:
  datasource:
    url: jdbc:mysql://203.195.155.161:3306/wx?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456x

mybatis-plus:
  mapper-locations: classpath:dwl/mapper/xml/*.xml
